on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:

      - name: Build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            VCS_REF=${{ github.sha }}
          load: true
          tags: cs50/cli:${{ github.sha }},cs50/cli:latest

      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push to Docker Hub
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/cli:${{ github.sha }}
          docker push cs50/cli:latest

      - name: Re-deploy depdendents
        if: ${{ github.ref == 'refs/heads/main' }}
        uses: actions/github-script@v5
        with:
          github-token: ${{ secrets.DEPLOY50_PAT }}
          script: |
            const dependents = [
                'codespace',
                'server'
            ];
            for (let dependent of dependents) {
                await github.rest.actions.createWorkflowDispatch({
                  owner: 'cs50',
                  repo: dependent,
                  workflow_id: 'main.yml',
                  ref: 'main'
                });
            }
