on: push
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Log into Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build
        uses: docker/build-push-action@v2
        with:
          load: true
          platforms: linux/amd64,linux/arm64
          tags: cs50/cli:${{ github.sha }},cs50/cli:latest
      - name: Push
        if: ${{ github.ref == 'refs/heads/main' }}
        run: |
          docker push cs50/cli:${{ github.sha }}
          docker push cs50/cli:latest
